name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
                         
    env:
      Solution_Name: fda-statistics.sln                                  

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Add Source
      run: dotnet nuget add source --username HydrologicEngineeringCenter --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/HydrologicEngineeringCenter/index.json"

    - name: Restore
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Debug
     
    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=Debug
        
    - name: Test
      run: dotnet test --no-build
      
    - name: Pack 
      run: dotnet pack --configuration Release --version-suffix "alpha-" + ${{ github.run_id }}
      shell: powershell
      
    - name: Publish
      run: dotnet nuget push "D:\a\fda-statistics\fda-statistics\Build\FDA2.0\*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate


  
